<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>Voting</b> system management' => '',
    '<i class="fa fa-pencil fa-lg"></i> &ensp;i' => '',
    '<i class="fa fa-plus fa-lg"></i> &ensp;i' => '',
    '<i class="fa fa-trash fa-lg"></i> &ensp;i' => '',
    'Admin panel' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Categories' => '',
    'Category' => '',
    'Category ID' => '',
    'Logout' => '',
    'Content En' => '',
    'Content Ru' => '',
    'Contest' => '',
    'Contest ID' => '',
    'Contests' => '',
    'Copyright &copy; {date} <a href="https://www.facebook.com/" target="_blank"> S&D </a>.</strong> All rightsreserved.' => '',
    'Create Category' => '',
    'Create Contest' => '',
    'Create Project' => '',
    'Create Team' => '',
    'Create Voter' => '',
    'Create category' => '',
    'Create contest' => '',
    'Create project' => '',
    'Create team' => '',
    'Create voter' => '',
    'Created At' => '',
    'Dashboard' => '',
    'Delete' => '',
    'Description En' => '',
    'Description Ru' => '',
    'Email' => '',
    'End Date' => '',
    'Home' => '',
    'I forgot my password' => '',
    'ID' => '',
    'Image' => '',
    'Name' => '',
    'No' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Permalink' => '',
    'Project' => '',
    'Projects' => '',
    'Public' => '',
    'Range' => '',
    'Reset' => '',
    'Result Panel' => '',
    'Role' => '',
    'Save' => '',
    'Score' => '',
    'Search' => '',
    'Sign in' => '',
    'Sign in to start your session' => '',
    'Start Date' => '',
    'Status' => '',
    'Team' => '',
    'Teams' => '',
    'Thank you!' => '',
    'The requested page does not exist.' => '',
    'Title' => '',
    'Title En' => '',
    'Title Ru' => '',
    'Login' => '',
    'URL to system: <a href="{url}">{url}</a>' => '',
    'Update' => '',
    'Update Category: {name}' => '',
    'Update Contest: {name}' => '',
    'Update Project: {name}' => '',
    'Update Team: {name}' => '',
    'Update Voter: {name}' => '',
    'Updated At' => '',
    'User ID' => '',
    'Username' => '',
    'Voter' => '',
    'Voter was created. The email has been successfully sent to the new voter.' => '',
    'Voters' => '',
    'Voters Limit' => '',
    'Voting System' => '',
    'Yes' => '',
    'You have successfully registered for {appName}' => '',
    'Your login in system: {login}' => '',
    'Your password in system: {password}' => '',
];
